language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic

matrix:
  fast_finish: true
  include:
    - php: 5.5.9
      env: setup=lowest
    - php: 5.5.9
      env: setup=stable

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi
  
script: phpunit --coverage-clover=coverage.clover
